import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { LiquidGlassProvider } from "@/components/os/LiquidGlassProvider";
import { ThemeProvider } from "@/components/os/ThemeProvider";
import { THEME_STORAGE_KEY } from "@/lib/theme";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Applies the persisted (or system) theme before hydration, so there's no
// flash of the wrong theme. Only ever reads our own localStorage key.
const themeInitScript = `(function () {
  try {
    var raw = localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)});
    var mode = raw ? JSON.parse(raw).state.mode : "system";
    var prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    var isDark = mode === "dark" || (mode === "system" && prefersDark);
    if (isDark) document.documentElement.classList.add("dark");
  } catch (e) {}
})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`} suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
        <ThemeProvider />
        <LiquidGlassProvider />
        {children}
      </body>
    </html>
  );
}
